{% set version = "1.0" %}

package:
  name: charls
  version: {{ version }}

source:
  url: https://github.com/team-charls/charls/archive/{{ version }}.tar.gz
  sha256: 028bacbd7e4d28b29921d6c076c851d3d2620621e48c9ebb9224bfd95e76c1ad


build:
  skip: True  # [win and vc<14]
  number: 3

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make   # [not win]
    - ninja  # [win]

test:
  commands:
    - test -f $PREFIX/lib/libCharLS${SHLIB_EXT}     # [unix]
    - test -f $PREFIX/include/interface.h       # [unix]
    - if not exist %LIBRARY_LIB%\\charls-2-x64.lib exit 1       # [win]
    - if not exist %LIBRARY_BIN%\\charls-2-x64.dll exit 1       # [win]
    - if not exist %LIBRARY_INC%\\charls\\charls.h exit 1       # [win]

about:
  home: https://github.com/team-charls/charls
  license: BSD-3-Clause
  license_family: BSD
  summary: 'CharLS is a C++ implementation of the JPEG-LS standard for lossless and near-lossless image compression and decompression. JPEG-LS is a low-complexity image compression standard that matches JPEG 2000 compression ratios.'

extra:
  recipe-maintainers:
    - hmaarrfk
